application: nich01as-us 
runtime: python27
api_version: 1
threadsafe: true
version: 1

handlers:
- url: /app
  static_dir: static/app/app 

- url: /.*
  script: heymenu.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest


